include ../Makefile.share

vrpn_headerPrint:
	$(MAKE) APP_NAME=vrpn_headerPrint \
                GENERATED_SRC= \
                EXCLUDE_SRC= \
                MAKECMDGOALS=""

vrpn_uiHeaderPrint:
	$(MAKE) APP_NAME=vrpn_uiHeaderPrint \
                GENERATED_SRC= \
                EXCLUDE_SRC= \
                MAKECMDGOALS=""

vrpn_streamTimeFix:
	$(MAKE) APP_NAME=vrpn_streamTimeFix \
                GENERATED_SRC= \
                EXCLUDE_SRC= \
                MAKECMDGOALS=""

streamPrint:
	$(MAKE) APP_NAME=streamPrint \
                GENERATED_SRC= \
                EXCLUDE_SRC= \
                MAKECMDGOALS=""

vrpn_newStreamPrint:
	$(MAKE) APP_NAME=vrpn_newStreamPrint \
                GENERATED_SRC= \
                EXCLUDE_SRC= \
                MAKECMDGOALS=""

streamToNewVrpn:
	$(MAKE) APP_NAME=streamToNewVrpn \
                GENERATED_SRC= \
                EXCLUDE_SRC= \
                MAKECMDGOALS=""
