/* The nanoManipulator and its source code have been released under the
 * Boost software license when nanoManipulator, Inc. ceased operations on
 * January 1, 2014.  At this point, the message below from 3rdTech (who
 * sublicensed from nanoManipulator, Inc.) was superceded.
 * Since that time, the code can be used according to the following
 * license.  Support for this system is now through the NIH/NIBIB
 * National Research Resource at cismm.org.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include "delay.h"

int Delay::s_inRealTimeSection = 0;
double Delay::s_iterationsPerMSec = 0.0;
DWORD Delay::s_dwPriorityClass = 0;
int Delay::s_iThreadPriority = 0;

#pragma optimize("",off)
void Delay::init()
{
  beginRealTimeSection();
  struct timeval t_start, t_end;
  gettimeofday(&t_start, NULL);
  gettimeofday(&t_end, NULL);
  double delta_t = vrpn_TimevalMsecs(t_end) - vrpn_TimevalMsecs(t_start);
  int numIterations = 0;
  // wait for one increment to occur
  while (delta_t < 1.0) {
    gettimeofday(&t_end, NULL);
    delta_t = vrpn_TimevalMsecs(t_end) - vrpn_TimevalMsecs(t_start);
  }
  t_start = t_end;
  delta_t = 0;
  // now wait for one complete cycle
  while (delta_t < 1.0) {
    gettimeofday(&t_end, NULL);
    delta_t = vrpn_TimevalMsecs(t_end) - vrpn_TimevalMsecs(t_start);
    numIterations++;
  }

  s_iterationsPerMSec = (double)numIterations/delta_t;
  endRealTimeSection();
}
#pragma optimize("",on)

void Delay::beginRealTimeSection()
{
  if (!s_inRealTimeSection) {
    s_dwPriorityClass = GetPriorityClass(GetCurrentProcess());
    s_iThreadPriority = GetThreadPriority(GetCurrentThread());
    SetPriorityClass( GetCurrentProcess() , REALTIME_PRIORITY_CLASS );
    SetThreadPriority( GetCurrentThread(), THREAD_PRIORITY_TIME_CRITICAL );
  }
  s_inRealTimeSection++;
}

void Delay::endRealTimeSection()
{
  if (!s_inRealTimeSection) return;
  s_inRealTimeSection--;
  if (!s_inRealTimeSection) {
    SetPriorityClass( GetCurrentProcess() , s_dwPriorityClass );
    SetThreadPriority( GetCurrentThread(), s_iThreadPriority );
  }
}

#pragma optimize("",off)
void Delay::busyWaitSleep(double time_msec)
{
  int numIterationsToDo = time_msec*s_iterationsPerMSec;
  int i;
  struct timeval t_start, t_end;
  int numIterations;

  double delta_t;
  gettimeofday(&t_start, NULL);
  for (i = 0; i < numIterationsToDo; i++) {
    gettimeofday(&t_end, NULL);
    delta_t = vrpn_TimevalMsecs(t_end) - vrpn_TimevalMsecs(t_start);
    numIterations++;
  }
}
#pragma optimize("",on)
