USES_LIBS := nmMP ImgFormat nmReg nmImageViewer nmBase vrpn quat

LATE_INCLUDE_PATH := -I/afs/unc/proj/stm/src/external/sgi_irix.n32/include
LATE_LOAD_PATH := -L/afs/unc/proj/stm/src/external/sgi_irix.n32/lib

include ../Makefile.share
