#!/bin/sh
#
# Find the right ./XXX executable to run.
# Depends on environment ($MY_NANO_???_DIR) and system ($HW_OS).

APP_EXE=nano;
APP_DIR=app/$APP_EXE;

FULL_EXE=`../app_exec $APP_DIR $APP_EXE`;
FULL_APP_DIR=`../app_dir $APP_DIR`;

echo $FULL_EXE $*
exec purify_proto -cache-dir=$FULL_APP_DIR $FULL_EXE $*
