/* The nanoManipulator and its source code have been released under the
 * Boost software license when nanoManipulator, Inc. ceased operations on
 * January 1, 2014.  At this point, the message below from 3rdTech (who
 * sublicensed from nanoManipulator, Inc.) was superceded.
 * Since that time, the code can be used according to the following
 * license.  Support for this system is now through the NIH/NIBIB
 * National Research Resource at cismm.org.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include "Tcl_Interpreter.h"

#include <tcl.h>
#include <tk.h>

#include <blt.h>

#ifndef NO_ITCL
#include <itcl.h>
#include <itk.h>
#endif

// for some reason blt.h doesn't declare this procedure.
// I copied this prototype from bltUnixMain.c, but I had to add
// the "C" so it would link with the library.
extern "C" int Blt_Init (Tcl_Interp *interp);
extern "C" int Blt_SafeInit(Tcl_Interp *interp);

Tcl_Interp *Tcl_Interpreter::tk_control_interp = NULL;

Tcl_Interp *Tcl_Interpreter::getInterpreter()
{
  if (!tk_control_interp) {
    if (initTclTk()) {
      if (tk_control_interp) {
          Tcl_DeleteInterp(tk_control_interp);
        tk_control_interp = NULL;
      }
    }
  }
  return tk_control_interp; 
}

int Tcl_Interpreter::initTclTk()
{
  Tk_Window       tk_control_window;

  Tcl_Interp * my_tk_control_interp = Tcl_CreateInterp();

#if defined (_WIN32) && !defined (__CYGWIN__)
  if (Tcl_InitStubs(my_tk_control_interp, TCL_VERSION, 1) == NULL) {
      fprintf(stderr, "Non matching version of tcl and tk\n");
      return -1;
  }
#endif
  /* Start a Tcl interpreter */
  if (Tcl_Init(my_tk_control_interp) == TCL_ERROR) {
      fprintf(stderr,
         "Tcl_Init failed: %s\n",Tcl_GetStringResult(my_tk_control_interp));
      return -1;
  }

  /* Initialize Tk using the Tcl interpreter */
  if (Tk_Init(my_tk_control_interp) == TCL_ERROR) {
      fprintf(stderr,
          "Tk_Init failed: %s\n",Tcl_GetStringResult(my_tk_control_interp));
      return -1;
  }
  Tcl_StaticPackage(my_tk_control_interp, "Tk", Tk_Init, Tk_SafeInit);

  /* Initialize Tcl packages */
  if (Blt_Init(my_tk_control_interp) == TCL_ERROR) {
      fprintf(stderr,
        "Package_Init failed: %s\n",Tcl_GetStringResult(my_tk_control_interp));
      return -1;
  }
  Tcl_StaticPackage(my_tk_control_interp, "Blt", Blt_Init, Blt_SafeInit);

#ifndef NO_ITCL
  if (Itcl_Init(my_tk_control_interp) == TCL_ERROR) {
      fprintf(stderr,
        "Package_Init failed: %s\n",Tcl_GetStringResult(my_tk_control_interp));
      return(-1);
  }
  if (Itk_Init(my_tk_control_interp) == TCL_ERROR) {
      fprintf(stderr,
         "Package_Init failed: %s\n",Tcl_GetStringResult(my_tk_control_interp));
      return(-1);
  }
  Tcl_StaticPackage(my_tk_control_interp, "Itcl", Itcl_Init, Itcl_SafeInit);
  Tcl_StaticPackage(my_tk_control_interp, "Itk", Itk_Init, 
                    (Tcl_PackageInitProc *) NULL);
#endif 
  // Check to see if we have a Tk main window.
  tk_control_window = Tk_MainWindow(my_tk_control_interp);
  if (tk_control_window == NULL) {
      fprintf(stderr,"Tk can't get main window: %s\n",
              Tcl_GetStringResult(my_tk_control_interp));
      return(-1);
  }
  tk_control_interp = my_tk_control_interp;

  return 0;
}

