####################################################
# This is the Makefile which works on a PC,
# using the Cygnus stuff to provide a Unix
# environment on top of Windows NT.
#
####################################################
# Define this when you are using OpenGL
#
GL_LIBS = -lglu32 -lopengl32


####################################################
# Define this to be glut
GLUT_LIBS = -lglut

####################################################
# Define this to be your X libraries
SYS_LIBS = -lwsock32 -luser32 -lgdi32 -lcomdlg32
#SYS_LIBS = -lwsock32 -luser32 -lgdi32 -lcomdlg32 -lkernel32 -lwinspool -ladvapi32 -lshell32 -lole32 -loleaut32 -luuid -lodbc32 -lodbccp32 


#kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib 
#advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib 


EXT = .exe

all: warrencntsim

warrencntsim : warrencntsim.o vec2d.o ppm.o cnt_ia.o cnt_filter.o cnt_glue.o
	g++ -DGLUT -o warrencntsim warrencntsim.o vec2d.o ppm.o cnt_ia.o cnt_filter.o cnt_glue.o $(GLUT_LIBS) $(GL_LIBS) $(SYS_LIBS)

.cpp.o:
	g++ -DGLUT -c $<

clean:
	-rm -f *.o
	-rm warrencntsim$(EXT)


