#!/bin/sh
#
# Find the right ./XXX executable to run.
# Depends on environment ($MY_NANO_???_DIR) and system ($HW_OS).

APP_EXE=afmcntsim;
APP_DIR=app/afmsim;

FULL_EXE=`../app_exec $APP_DIR $APP_EXE`;

echo $FULL_EXE $*
exec gdb $FULL_EXE $*
