/* The nanoManipulator and its source code have been released under the
 * Boost software license when nanoManipulator, Inc. ceased operations on
 * January 1, 2014.  At this point, the message below from 3rdTech (who
 * sublicensed from nanoManipulator, Inc.) was superceded.
 * Since that time, the code can be used according to the following
 * license.  Support for this system is now through the NIH/NIBIB
 * National Research Resource at cismm.org.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/


#ifndef dbimage_h
#define dbimage_h

// #include <string.h>

class DBImage {
public:
    
    DBImage(char* filename);
    ~DBImage();

    double* const double_array() { return _da; }

    // Here the intensities are scaled to [0, 255].
    unsigned char* const byte_array() { return _ba; }

    unsigned   xdim() const { return _xdim; }
    unsigned   ydim() const { return _ydim; }

    double pixval(int x, int y) { return _da[y * _xdim + x]; }

    double  min_pixval() const { return _min_pixval; }
    double  max_pixval() const { return _max_pixval; }
    double  x_nm_perpixel() const { return _x_nm_perpixel; }
    double  y_nm_perpixel() const { return _y_nm_perpixel; }

private:
    double* _da;
    unsigned char* _ba;
    int _xdim;
    int _ydim;
    double _min_pixval;    // Height or intensity.
    double _max_pixval;
    double _x_nm_perpixel; // x and y scales in nanometers per pixel
    double _y_nm_perpixel;

};


#endif // dbimage_h
