/* The nanoManipulator and its source code have been released under the
 * Boost software license when nanoManipulator, Inc. ceased operations on
 * January 1, 2014.  At this point, the message below from 3rdTech (who
 * sublicensed from nanoManipulator, Inc.) was superceded.
 * Since that time, the code can be used according to the following
 * license.  Support for this system is now through the NIH/NIBIB
 * National Research Resource at cismm.org.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <stdio.h>
#include <stdlib.h>
#include "vrpn_Connection.h"
#include "vrpn_GPIBDeviceServer.h"

unsigned short def_port_no = 4545;

//--------------------------------------------------------------------------
// Handles VRPN messages

int handle_any_print (void * userdata, vrpn_HANDLERPARAM p) {
  vrpn_Connection * c = (vrpn_Connection *) userdata;

  fprintf(stderr, "Got message \"%s\" from \"%s\".\n",
          c->message_type_name(p.type), c->sender_name(p.sender));

  return 0;  // non-error completion
}



void main (unsigned argc, char *argv[])
{

#ifdef _WIN32
	WSADATA wsaData; 
	int status;
    if ((status = WSAStartup(MAKEWORD(1,1), &wsaData)) != 0) {
         fprintf(stderr, "WSAStartup failed with %d\n", status);
    } else {
		 //fprintf(stderr, "WSAStartup success\n");
	}
#endif

	vrpn_Synchronized_Connection *	connection;
	vrpn_GPIBDeviceServer * gpib_server;

	connection = new vrpn_Synchronized_Connection(def_port_no);

	// DEBUG print all message, incoming and outgoing, 
	// sent over our VRPN connection
	//connection->register_handler(vrpn_ANY_TYPE, handle_any_print,
	//			    connection);
         // defaults to vrpn_SENDER_ANY

	
	gpib_server = new vrpn_GPIBDeviceServer("GPIBServer@argon", connection);

	if (gpib_server == NULL) {
		fprintf(stderr, "Couldn't create gpib_server\n");
		exit(1);
	}
  struct timeval delay;

  delay.tv_sec = 0L;
  delay.tv_usec = 10L;

	// Loop forever calling the mainloop()s for all devices
	while (1) {

		// Put in a sleep to free up CPU cycles.
		vrpn_SleepMsecs(1);

		// Send/receive messages from our vrpn connection.
		// Delay a very short time to avoid using 100% cpu time.
		gpib_server->mainloop(&delay);
	}
}
