/* The nanoManipulator and its source code have been released under the
 * Boost software license when nanoManipulator, Inc. ceased operations on
 * January 1, 2014.  At this point, the message below from 3rdTech (who
 * sublicensed from nanoManipulator, Inc.) was superceded.
 * Since that time, the code can be used according to the following
 * license.  Support for this system is now through the NIH/NIBIB
 * National Research Resource at cismm.org.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef NMB_IMG_MAGICK_H
#define NMB_IMG_MAGICK_H
/*===3rdtech===
  Copyright (c) 2001 by 3rdTech, Inc.
  All Rights Reserved.

  This file may not be distributed without the permission of 
  3rdTech, Inc. 
  ===3rdtech===*/
class BCGrid;
class nmb_Image;

class nmb_ImgMagick {
public:
    static void initMagick(char * argv);

    /// Read an image file using the ImageMagick library's routines. 
    static int readFileMagick(const char * filename, const char * name, 
                              BCGrid * grid);
    /// Write an image file using the ImageMagick library's routines. 
    static int writeFileMagick(const char * filename, 
                               const char * mgk_filetype, 
                               int cols, int rows, 
                               int bpp, unsigned char * pixels);
    /// Write an image file using the ImageMagick library's routines, from /
    /// data in a BCPlane object.
    static int writeFileMagick(const char * filename, 
                               const char * mgk_filetype, 
                               BCPlane * plane);

    /// Write an image file using the ImageMagick library's routines, from /
    /// data in an nmb_Image object
    static int writeFileMagick(const char * filename,
                               const char * mgk_filetype,
                               nmb_Image * image);
private:
    ///Static object, should never be constructed
    nmb_ImgMagick ();
};

#endif
