/* The nanoManipulator and its source code have been released under the
 * Boost software license when nanoManipulator, Inc. ceased operations on
 * January 1, 2014.  At this point, the message below from 3rdTech (who
 * sublicensed from nanoManipulator, Inc.) was superceded.
 * Since that time, the code can be used according to the following
 * license.  Support for this system is now through the NIH/NIBIB
 * National Research Resource at cismm.org.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/*===3rdtech===
  Copyright (c) 2001 by 3rdTech, Inc.
  All Rights Reserved.

  This file may not be distributed without the permission of 
  3rdTech, Inc. 
  ===3rdtech===*/
#include "nmb_String.h"

#include <string.h>  // strcmp(), strncmp(), strncpy()
#include <stdio.h>  // fprintf()

#ifdef _WIN32
// turns off warning C4290: C++ Exception Specification ignored
#pragma warning( push )
#pragma warning( disable : 4290 4996 )
#endif

nmb_ListOfStrings::nmb_ListOfStrings (void) :
    d_numEntries (0) {
    for(int i =0; i< NUM_ENTRIES; i++) {
	d_entries[i] = new char[nmb_STRING_LENGTH + 1];
    }
}

// virtual
nmb_ListOfStrings::~nmb_ListOfStrings (void) {

//int i;
//fprintf(stderr, "Deleting list of strings:\n");
//for (i = 0; i < d_numEntries; i++)
//fprintf(stderr, "    %s\n", d_entries[i]);

  while (d_numEntries && !deleteEntry(d_entries[0])) ;
  for(int i =0; i< NUM_ENTRIES; i++) {
      delete [] d_entries[i];
  }
  
}
/** Returns an entry in this list, by numerical index.
Returns NULL if index is not valid for this list.
*/
const char * nmb_ListOfStrings::entry (int i) const
{ 
    if ((i <0) || (i>=d_numEntries)) return NULL;
    return d_entries[i]; 
}

/** Checks to see if the character string /a name is 
in this list. If it is, it returns it's numerical index.
If not, returns -1
*/
int nmb_ListOfStrings::getIndex (const char * name) const
{ 
    for (int i = 0; i < d_numEntries; i++) {
        if (strncmp(name, d_entries[i], nmb_STRING_LENGTH) == 0) {
            return i;
        }
    }
    return -1;
}

int nmb_ListOfStrings::clearList () 
{
    d_numEntries = 0;
    return 0;
}

int nmb_ListOfStrings::addEntry (const char * newEntry) 
{
  int i;

  // Make sure there is enough room for another entry.
  if (d_numEntries >= NUM_ENTRIES) {
    return 1;
  }

  // Make sure the entry is not already on the list
  for (i = 0; i < d_numEntries; i++) {
    if (!strncmp(d_entries[i], newEntry, nmb_STRING_LENGTH)) {
      return 2;
    }
  }

  strncpy(d_entries[d_numEntries], newEntry, nmb_STRING_LENGTH);
  d_numEntries++;

  return 0;
}

int nmb_ListOfStrings::deleteEntry (const char * oldEntry) {
  int i;
  int ret = 0;

  // Find it.
  for (i = 0; (i < d_numEntries) &&
              strncmp(d_entries[i], oldEntry, nmb_STRING_LENGTH); i++) ;
  if (i == d_numEntries) {
    return 1;
  }

  strncpy(d_entries[i], d_entries[d_numEntries - 1],
          nmb_STRING_LENGTH);
  d_numEntries--;

  return ret;
}

int nmb_ListOfStrings::copyList(nmb_ListOfStrings * newList)
{
  int i;
  for (i = 0; i < newList->d_numEntries; i++) {
      strncpy(d_entries[i], newList->d_entries[i], 
	      nmb_STRING_LENGTH);
  }
  d_numEntries = newList->d_numEntries;
  return 0;

}

nmb_ListOfStrings * allocate_nmb_ListOfStrings() {
  return new nmb_ListOfStrings ();
}


nmb_String::nmb_String (const char * initialValue) 
{
  Set(initialValue);

}

// virtual
nmb_String::~nmb_String (void) {

}

nmb_String::operator const char * (void) const {
  return d_myString;
}

const char * nmb_String::string (void) const {
  return d_myString;
}

const char * nmb_String::lastString (void) const {
  return d_myLastString;
}

//void nmb_String::setCallback

/*
// virtual
int nmb_String::bindList (nmb_ListOfStrings * list) {

  // Can be used to set NULL => non-NULL
  //          or to set non-NULL => NULL,
  //            but not non-NULL => non-NULL.

  if (list && d_myList) {
    fprintf(stderr, "nmb_String::bindList:  Called twice.\n");
    return -1;
  }

  d_myList = list;

  if (list)
    list->addString(this);

  return 0;
}
*/

// virtual
const char * nmb_String::operator = (const char * v) {
  if (!v) {
    d_myString[0] = 0;
  } else {
    strncpy(d_myString, v, nmb_STRING_LENGTH);
  }

  return d_myString;
}
  

// Same implementation, but different signature...

// virtual
const char * nmb_String::operator = (char * v) {
  if (!v) {
    d_myString[0] = 0;
  } else {
    strncpy(d_myString, v, nmb_STRING_LENGTH);
  }

  return d_myString;
}
  

// virtual
void nmb_String::Set (const char * value) {
  // Need to invoke operator = in case it's been redefined
  // by derived class.
  operator = (value);
  strncpy(d_myLastString, value, nmb_STRING_LENGTH);
}


nmb_String * allocate_nmb_String (const char * iv) {
  return new nmb_String (iv);
}

#ifdef _WIN32
#pragma warning( pop )
#endif
