USES_LIBS := tclLinkVar nmBase nmGraphics ImgFormat nmMScope vrpn vogl quat

# normal.c is in here, and it uses mf.h from the app/nano directory.
# Should be removed soon. 
NAUGHTY := 1

EXCLUDE_SRC := testComponent.C

include ../Makefile.share
