USES_LIBS := nmMP tclLinkVar nmBase nmImageViewer nmGraphics nmMScope vrpn vogl quat

USES_EXTERNAL_LIBS := TclTk

# normal.c is in here, and it uses mf.h from the app/nano directory.
# Should be removed soon. 
NAUGHTY := 1

EXCLUDE_SRC := testComponent.C

include ../Makefile.share
