/* The nanoManipulator and its source code have been released under the
 * Boost software license when nanoManipulator, Inc. ceased operations on
 * January 1, 2014.  At this point, the message below from 3rdTech (who
 * sublicensed from nanoManipulator, Inc.) was superceded.
 * Since that time, the code can be used according to the following
 * license.  Support for this system is now through the NIH/NIBIB
 * National Research Resource at cismm.org.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/*===3rdtech===
  Copyright (c) 2000 by 3rdTech, Inc.
  All Rights Reserved.

  This file may not be distributed without the permission of 
  3rdTech, Inc. 
  ===3rdtech===*/
#include <math.h>
#include <blt.h>  // for BLT vector class and functions.
#if defined (__CYGWIN__) || (linux) || (_WIN32)
#include <float.h> // for FLT_MAX
#endif


#include <BCGrid.h>
#include <BCPlane.h>
#include <nmb_String.h>
#include <Tcl_Interpreter.h>
#include "nmui_CrossSection.h"

#ifndef min
#define min(a,b) ((a)<(b)?(a):(b))
#endif
#ifndef max
#define max(a,b) ((a)>(b)?(a):(b))
#endif

nmui_CrossSection::nmui_CrossSection (void) :
    d_snap_to_45("xs_snap_to_45", 0),
    d_vary_width("xs_vary_width", 0),
    d_max_points ("xs_max_num_points", 4000),
    d_clear_zero("xs_clear_0",0),
    d_clear_one("xs_clear_1", 0),
    d_data_update("xs_data_update", 0),
    d_length(0),
    d_numDataVectors(0)
{
    d_hide[0] = 1;
    d_hide[1] = 1;
    d_first_call[0] = 1;
    d_first_call[1] = 1;

    d_max_points.addCallback(handle_MaxPointsChange, this);
    d_clear_zero.addCallback(handle_ClearZero, this);
    d_clear_one.addCallback(handle_ClearOne, this);

    path[0] = NULL;
    path[1] = NULL;
    for (int j = 0; j < 2; j++) {
        for (int i = 0; i < nmb_ListOfStrings::NUM_ENTRIES; i++ ) {
            data[j][i] = NULL;
        }
    }

}

nmui_CrossSection::~nmui_CrossSection (void) {
  d_max_points.bindConnection(NULL);
}


// static
int nmui_CrossSection::ShowCrossSection(BCGrid* grid, 
                                        nmb_ListOfStrings * plane_names, 
                                        int id, int /*hide*/,
                                        float center_x,float center_y, 
                                        float width1, float width2, 
                                        float angle)
{

  //fprintf(stderr, "nmui_CrossSection::ShowCrossSection\n");

   //int	numValues;
   char    command[300];
   char    str[300];
   Blt_Vector *dataVecPtr = NULL;
   Blt_Vector *pathVecPtr = NULL;
   int i,j;

   if (id < 0 || id > 1) {
       printf("ShowCrossSection: bogus id\n");
       return -1;
   }
   // do nothing if cross section hidden. 
   if (d_hide[id]) return 0;

      //set up the path vector first.
      sprintf(str, "xs%d_Path", id);
      if (!Blt_VectorExists(Tcl_Interpreter::getInterpreter(), str))  {
	 //create the vector
	 if (Blt_CreateVector(Tcl_Interpreter::getInterpreter(), str,0,&pathVecPtr) != TCL_OK) {
	    fprintf(stderr, "Tcl_Eval(BLT_CreateVector) failed: %s\n",
		    Tcl_Interpreter::getInterpreter()->result);
	    return -1;
	 }
      } else {
          if (Blt_GetVector(Tcl_Interpreter::getInterpreter(), str, &pathVecPtr) != TCL_OK) {
              fprintf(stderr, "Tcl_Eval(BLT_GetVector) failed: %s\n",
                      Tcl_Interpreter::getInterpreter()->result);
              return -1;
          }
      }
      int length = max(grid->numX(), grid->numY());
      if (d_length != length)  {
          if (path[id] != NULL) {
              delete [] path[id];
              path[id] = NULL;
          }
          for (i = 0; i < nmb_ListOfStrings::NUM_ENTRIES; i++ ) {
              if (data[id][i] != NULL) {
                  delete [] data[id][i];
                  data[id][i] = NULL;
              }
          }
          d_length = length;
      }
      if (path[id] == NULL) {
          path[id] = new double[d_length];
      }
      double step = (width1 + width2)/(d_length-1);
      for ( j=0; j<d_length; j++) {
          path[id][j] = j*step;
      }
      if (Blt_ResetVector(pathVecPtr, path[id], d_length, d_length,
                          TCL_STATIC) != TCL_OK) {
          fprintf(stderr, "Tcl_Eval(BLT_ResetVector) failed: %s\n",
                  Tcl_Interpreter::getInterpreter()->result);
      }

      // create a vector for each data plane
      // and attach it to a graph in the stripchart
      for ( i = 0; i < plane_names->numEntries() ; i++) {
          BCPlane * plane = grid->getPlaneByName(plane_names->entry(i));
          if (!plane) continue;
          // make sure we include name and units in the vector name. 
          sprintf(str,"xs%d_%s_%s", id, plane->name()->c_str(), 
		 plane->units()->c_str());

	 // remove spaces and "-", they are bad for vector names.
	 for (unsigned int k = 0; k < strlen(str); k++){
	    if (str[k] == ' '||str[k] == '-')
	       str[k] = '_';
	 }

	 if (!Blt_VectorExists(Tcl_Interpreter::getInterpreter(), str))  {
	    if (Blt_CreateVector(Tcl_Interpreter::getInterpreter(), str, 0, &dataVecPtr) != TCL_OK) {
	       fprintf(stderr, "Tcl_Eval(BLT_CreateVector) failed: %s\n",
		       Tcl_Interpreter::getInterpreter()->result);
	       return -1;
	    }
            //printf("created %s\n", str);
	 } else {
             if (Blt_GetVector(Tcl_Interpreter::getInterpreter(), str, &dataVecPtr) != TCL_OK) {
	       fprintf(stderr, "Tcl_Eval(BLT_GetVector) failed: %s\n",
		       Tcl_Interpreter::getInterpreter()->result);
	       return -1;
	    }
         }

//           strcpy(me->d_dataVectorNames[me->d_numDataVectors], str);
//           me->d_numDataVectors++;
//           if (me->d_numDataVectors == MAX_DATA_VECTORS) {
//              fprintf(stderr, "Stripchart Error: out of space (>32 data vectors)\n");
//  	    break;
//           }
         double stepx = ((width1 + width2)*cos(angle))/(d_length-1);
         double stepy = ((width1 + width2)*sin(angle))/(d_length-1);
         double startx = center_x - width1*cos(angle);
         double starty = center_y - width1*sin(angle);
         
         if (data[id][i] == NULL) {
             data[id][i] = new double [d_length];
         }
         // Read data values from along the cross section. 
         for (int j=0; j<d_length; j++) {
             data[id][i][j] = plane->interpolatedValueAt(startx + j*stepx,
                                                         starty + j*stepy);
         }
         // Send data to tcl to be displayed. 
         if (Blt_ResetVector(dataVecPtr, &(data[id][i][0]), d_length, d_length,
                             TCL_STATIC) != TCL_OK) {
	       fprintf(stderr, "Tcl_Eval(BLT_ResetVector) failed: %s\n",
		       Tcl_Interpreter::getInterpreter()->result);
         }
      }
      if (d_first_call[id]) {
          d_first_call[id] = 0;
          sprintf(command, "create_new_cross_section %d", id);
          TCLEVALCHECK(Tcl_Interpreter::getInterpreter(), command);
      }
      // Trigger data update in tcl interface. 
      d_data_update = id;
   
   return 0;
}


// static
void nmui_CrossSection::handle_MaxPointsChange(vrpn_int32 new_value, void * userdata)
{
    // Maximum points used in the cross section.

    // Not in UI yet. 
}

void nmui_CrossSection::handle_ClearZero(vrpn_int32 new_value, void * userdata)
{
   nmui_CrossSection *me = (nmui_CrossSection *)userdata;
   char command[100];
   sprintf(command, "clear_cross_section 0");
   TCLEVALCHECK2(Tcl_Interpreter::getInterpreter(), command);
   me->d_hide[0] = 1;
   me->d_first_call[0] = 1;
}

void nmui_CrossSection::handle_ClearOne(vrpn_int32 new_value, void * userdata)
{
   nmui_CrossSection *me = (nmui_CrossSection *)userdata;
   char command[100];
   sprintf(command, "clear_cross_section 1");
   TCLEVALCHECK2(Tcl_Interpreter::getInterpreter(), command);
   me->d_hide[1] = 1;
   me->d_first_call[1] = 1;
}

void nmui_CrossSection::SetupSynchronization(nmui_Component * container)
{
  container->add(&d_max_points);
}

void nmui_CrossSection::TeardownSynchronization(nmui_Component * container)
{
  container->remove(&d_max_points);
}

