/* The nanoManipulator and its source code have been released under the
 * Boost software license when nanoManipulator, Inc. ceased operations on
 * January 1, 2014.  At this point, the message below from 3rdTech (who
 * sublicensed from nanoManipulator, Inc.) was superceded.
 * Since that time, the code can be used according to the following
 * license.  Support for this system is now through the NIH/NIBIB
 * National Research Resource at cismm.org.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include "nmui_SurfaceFeatures.h"

#include <nmb_Dataset.h>

#include <nmm_MicroscopeRemote.h>

#include "nmui_HapticSurface.h"

// BUG - violates librariness
#include "microscape.h"  // for adhesion_slider_min &c, MIN_K and MAX_K
#include "interaction.h"  // for knob #defines
#include "globals.h"  // for Arm_knobs[]

#ifndef min
#define min(a,b) ((a)<(b)?(a):(b))
#endif
#ifndef max
#define max(a,b) ((a)>(b)?(a):(b))
#endif








nmui_SurfaceFeatureStrategy::nmui_SurfaceFeatureStrategy (void) {

}

// virtual
nmui_SurfaceFeatureStrategy::~nmui_SurfaceFeatureStrategy (void) {

}

//virtual
vrpn_bool nmui_SurfaceFeatureStrategy::buzzingEnabled (nmb_Dataset *, nmm_Microscope_Remote *) const {
  return vrpn_false;
}

//virtual
vrpn_bool nmui_SurfaceFeatureStrategy::bumpsEnabled (nmb_Dataset *, nmm_Microscope_Remote *) const {
  return vrpn_false;
}

// virtual
double nmui_SurfaceFeatureStrategy::pointAdhesionValue (nmb_Dataset *, nmm_Microscope_Remote * ) {
  return 0.0;
}

// virtual
double nmui_SurfaceFeatureStrategy::scaledPointBuzzAmplitude (nmb_Dataset *, nmm_Microscope_Remote * ) {
  return 0.0;
}

// virtual
double nmui_SurfaceFeatureStrategy::scaledPointBumpSizeValue (nmb_Dataset *, nmm_Microscope_Remote * ) {
  return 0.0;
}

// virtual
double nmui_SurfaceFeatureStrategy::pointComplianceValue (nmb_Dataset *, nmm_Microscope_Remote * ) {
  return max( 0.01, min(1.0, (double)default_spring_k) );
}

// virtual
double nmui_SurfaceFeatureStrategy::pointFrictionValue (nmb_Dataset *, nmm_Microscope_Remote * ) {
  return max(0.0, Arm_knobs[FRICTION_KNOB]);
}

// virtual
double nmui_SurfaceFeatureStrategy::dynamicFrictionKspring
        (double staticFrictionKspring, nmb_Dataset *, nmm_Microscope_Remote *) {
  return 0.5 * staticFrictionKspring;
}


nmui_SurfaceFeatures::nmui_SurfaceFeatures (void) :
    d_firstExecution (vrpn_true),
    d_useLinearBuzzing (vrpn_false),
    d_useLinearBumps (vrpn_false),
    d_useLinearFriction (vrpn_false),
    d_adhesionConstant (12000.0),
    d_buzzFrequency (115.0),
    d_complianceGain (1.3),
    d_strategy (NULL) {

}

nmui_SurfaceFeatures::~nmui_SurfaceFeatures (void) {

}

void nmui_SurfaceFeatures::update (nmb_Dataset * dataset, nmm_Microscope_Remote * scope) {

  if (d_strategy) {

    specifyAdhesion(dataset, scope);
    specifyBuzzAmplitude(dataset, scope);
    specifyBumpSize(dataset, scope);
    specifyCompliance(dataset, scope);
    specifyFriction(dataset, scope);

  }

  d_firstExecution = vrpn_false;
}

void nmui_SurfaceFeatures::setSurfaceFeatureStrategy
        (nmui_SurfaceFeatureStrategy * fs) {
  d_strategy = fs;
}



void nmui_SurfaceFeatures::useLinearBuzzing (vrpn_bool on) {
  d_useLinearBuzzing = on;
}

void nmui_SurfaceFeatures::useLinearBumps (vrpn_bool on) {
  d_useLinearBumps = on;
}

void nmui_SurfaceFeatures::useLinearFriction (vrpn_bool on) {
  d_useLinearFriction = on;
}



void nmui_SurfaceFeatures::setBuzzFrequency (double hz) {
  d_buzzFrequency = hz;
}

void nmui_SurfaceFeatures::setComplianceGain (double gain) {
  d_complianceGain = gain;
}

void nmui_SurfaceFeatures::setAdhesionConstant (double kAdh) {
  d_adhesionConstant = kAdh;
}



void nmui_SurfaceFeatures::specifyAdhesion (nmb_Dataset * dataset, nmm_Microscope_Remote * scope) {
  double adhesion_range;
  double adh;

  adh = d_strategy->pointAdhesionValue(dataset, scope);

  if (adhesion_slider_min != adhesion_slider_max) {
    adhesion_range = adhesion_slider_max - adhesion_slider_min;
    adh = (adh - adhesion_slider_min) / adhesion_range;

    adh = min(1.0, adh);
    adh = max(0.0, adh);

    adh *= d_adhesionConstant;
  }

  // do nothing
}

void nmui_SurfaceFeatures::specifyBuzzAmplitude (nmb_Dataset * dataset, nmm_Microscope_Remote * scope) {
  double amp;

  if (!d_strategy->buzzingEnabled(dataset, scope)) {
    setBuzzing(0.0);
    return;
  }

  amp = d_strategy->scaledPointBuzzAmplitude(dataset, scope);

  // Percieved magnitude of buzzing is proportional to x^0.95
  if (d_useLinearBuzzing) {
    amp = log(amp) / log(0.95);
  }

  // Limit to [0, 1]
  amp = min(1.0, amp);
  amp = max(0.0, amp);

  // Magic numbers from previous code
  amp = d_strategy->magicBuzzAmplitude(amp);

  setBuzzing(amp);
}

void nmui_SurfaceFeatures::specifyBumpSize (nmb_Dataset * dataset, nmm_Microscope_Remote * scope) {
  double wavelength;

  if (!d_strategy->bumpsEnabled(dataset, scope)) {
    setSurfaceTexture(0.0);
    return;
  }

  wavelength = d_strategy->scaledPointBumpSizeValue(dataset, scope);

  // Percieved magnitude of bumps is proportional to lambda^0.86
  if (d_useLinearBumps) {
    wavelength = log(wavelength) / log(0.86);
  }

  // Limit to [0, 1]
  wavelength = min(1.0, wavelength);
  wavelength = max(0.0, wavelength);

  // Magic numbers from previous code
  wavelength = d_strategy->magicBumpSize(wavelength);

  setSurfaceTexture(wavelength);

}

void nmui_SurfaceFeatures::specifyCompliance (nmb_Dataset * dataset, nmm_Microscope_Remote * scope) {
  double compliance_range;
  double kS;

  kS = d_strategy->pointComplianceValue(dataset, scope);

  if (compliance_slider_max != compliance_slider_min) {
    compliance_range = compliance_slider_max - compliance_slider_min;
    kS = (kS - compliance_slider_min) / compliance_range;

    // Compliance is perceptually linear, so we don't need to take logs.

    // Limit to [0, 1]
    kS = min(1.0, kS);
    kS = max(0.0, kS);

    // Gain compensation should almost certainly be AFTER we scale by
    // MIN_K and MAX_K, but this is a refactoring, not a bugfix.
    kS *= d_complianceGain;
    kS = kS * (MAX_K - MIN_K) + MIN_K;
  }

//fprintf(stderr, "Compliance is %.5f\n", kS);

  setCompliance(kS);
}

void nmui_SurfaceFeatures::specifyFriction (nmb_Dataset * dataset, nmm_Microscope_Remote * scope) {
  double friction_range;
  double localValue;
  double kS;
  double dynamic_kS;

  localValue = d_strategy->pointFrictionValue(dataset, scope);

  if (friction_slider_max != friction_slider_min) {
    friction_range = friction_slider_max - friction_slider_min;
    kS = (localValue - friction_slider_min) / friction_range;

    // Percieved magnitude of friction is proportional to x^1.5
    if (d_useLinearFriction) {
      kS = log(kS) / log(1.5);
    }

    // Limit to [0, 1]
    kS = min(1.0, kS);
    kS = max(0.0, kS);

  } else {

    kS = max(0.0, Arm_knobs[FRICTION_KNOB]);

  }

  dynamic_kS = d_strategy->dynamicFrictionKspring(kS, dataset, scope);
  setFriction(kS, dynamic_kS);
}






// virtual
void nmui_SurfaceFeatures::setFriction (double kS, double dynamic_kS) {
  if (forceDevice) {
    forceDevice->setSurfaceFstatic(kS);
    forceDevice->setSurfaceFdynamic(dynamic_kS);
  }
}

void nmui_SurfaceFeatures::setSurfaceTexture (double wavelength) {
  if (forceDevice) {
    forceDevice->setSurfaceTextureWavelength(wavelength);
    forceDevice->setSurfaceTextureAmplitude(0.1 * wavelength);
  }
}

void nmui_SurfaceFeatures::setBuzzing (double amp) {
  if (forceDevice) {
    forceDevice->setSurfaceBuzzFrequency(d_buzzFrequency);
    forceDevice->setSurfaceBuzzAmplitude(amp);
  }
}

void nmui_SurfaceFeatures::setCompliance (double kS) {
  if (forceDevice) {
    forceDevice->setSurfaceKspring(kS);
  }
}







nmui_PointFeatures::nmui_PointFeatures () :
    nmui_SurfaceFeatureStrategy () {

}

// virtual
nmui_PointFeatures::~nmui_PointFeatures (void) {

}



// virtual
vrpn_bool nmui_PointFeatures::buzzingEnabled (nmb_Dataset *, nmm_Microscope_Remote * scope) const {
    if (!scope) { 
        fprintf(stderr,"nmui_PointFeatures Error! no scope!\n"); 
        return vrpn_false; 
    }
  Point_value * value =
    scope->state.data.inputPoint->getValueByPlaneName
         (buzzPlaneName.string());
  double buzz_range = buzz_slider_max - buzz_slider_min;

  if (!buzz_range || !value) {
    return vrpn_false;
  }
  return vrpn_true;
}

// virtual
vrpn_bool nmui_PointFeatures::bumpsEnabled (nmb_Dataset *, nmm_Microscope_Remote * scope) const {
    if (!scope) { 
        fprintf(stderr,"nmui_PointFeatures Error! no scope!\n"); 
        return vrpn_false; 
    }
  Point_value * value =
    scope->state.data.inputPoint->getValueByPlaneName
         (bumpPlaneName.string());
  if ((bump_slider_max == bump_slider_min) || !value) {
    return vrpn_false;
  }

  return vrpn_true;
}



// virtual
double nmui_PointFeatures::pointAdhesionValue (nmb_Dataset *, nmm_Microscope_Remote * scope) {
    if (!scope) { 
        fprintf(stderr,"nmui_PointFeatures Error! no scope!\n"); 
        return nmui_SurfaceFeatureStrategy::pointAdhesionValue(dataset, scope);
    }
  Point_value * value =
    scope->state.data.inputPoint->getValueByPlaneName
         (adhesionPlaneName.string());

  if (!value) {
    return nmui_SurfaceFeatureStrategy::pointAdhesionValue(dataset, scope);
  }

  return value->value();
}

// virtual
double nmui_PointFeatures::scaledPointBuzzAmplitude (nmb_Dataset *, nmm_Microscope_Remote * scope) {
    if (!scope) { 
        fprintf(stderr,"nmui_PointFeatures Error! no scope!\n"); 
        return 0.0;
    }
  Point_value * value =
    scope->state.data.inputPoint->getValueByPlaneName
         (buzzPlaneName.string());
  double buzz_range = buzz_slider_max - buzz_slider_min;

  return (value->value() - buzz_slider_min) / buzz_range;
}

// virtual
double nmui_PointFeatures::pointFrictionValue (nmb_Dataset *, nmm_Microscope_Remote * scope) {
    if (!scope) { 
        fprintf(stderr,"nmui_PointFeatures Error! no scope!\n"); 
        return nmui_SurfaceFeatureStrategy::pointFrictionValue(dataset, scope);
    }
  Point_value * value =
    scope->state.data.inputPoint->getValueByPlaneName
         (frictionPlaneName.string());

  if (!value) {
    return nmui_SurfaceFeatureStrategy::pointFrictionValue(dataset, scope);
  }

  return value->value();
}

// virtual
double nmui_PointFeatures::scaledPointBumpSizeValue (nmb_Dataset *, nmm_Microscope_Remote * scope) {
    if (!scope) { 
        fprintf(stderr,"nmui_PointFeatures Error! no scope!\n"); 
        return 0.0; 
    }
  Point_value * value =
    scope->state.data.inputPoint->getValueByPlaneName
         (bumpPlaneName.string());
  double bump_range = bump_slider_max - bump_slider_min;

  if (bump_range && value) {
    return (value->value() - bump_slider_min) / bump_range;
  } else {
    return 0.0;
  }
}


// virtual
double nmui_PointFeatures::magicBuzzAmplitude (double amp) {
  return 0.002 * amp;
}

// virtual
double nmui_PointFeatures::magicBumpSize (double wavelength) {
  return 0.01 * wavelength;
}



// virtual
double nmui_PointFeatures::dynamicFrictionKspring (double /*kS*/, nmb_Dataset * dataset, nmm_Microscope_Remote * scope) {
  return nmui_SurfaceFeatureStrategy::pointFrictionValue(dataset, scope);
}






nmui_GridFeatures::nmui_GridFeatures (nmui_HSCanned * surface) :
    nmui_SurfaceFeatureStrategy (),
    d_hapticSurface (surface) {

}

// virtual
nmui_GridFeatures::~nmui_GridFeatures (void) {

}



// virtual
vrpn_bool nmui_GridFeatures::buzzingEnabled (nmb_Dataset * dataset, nmm_Microscope_Remote * scope) const {
  BCPlane * plane =
    dataset->inputGrid->getPlaneByName(buzzPlaneName.string());

  if (!plane || (buzz_slider_max == buzz_slider_min)) {
    return vrpn_false;
  }

  return vrpn_true;
}

// virtual
vrpn_bool nmui_GridFeatures::bumpsEnabled (nmb_Dataset * dataset, nmm_Microscope_Remote * scope) const {
  BCPlane * plane =
    dataset->inputGrid->getPlaneByName(bumpPlaneName.string());

  if ((bump_slider_max == bump_slider_min) || !plane) {
    return vrpn_false;
  }

  return vrpn_true;
}

// virtual
double nmui_GridFeatures::pointAdhesionValue (nmb_Dataset * dataset, nmm_Microscope_Remote * scope) {
  BCPlane * plane =
    dataset->inputGrid->getPlaneByName(adhesionPlaneName.string());

  if (!plane) {
    return nmui_SurfaceFeatureStrategy::pointAdhesionValue(dataset, scope);
  }

  return plane->value(d_hapticSurface->getGridX(),
                      d_hapticSurface->getGridY());
}

// virtual
double nmui_GridFeatures::scaledPointBuzzAmplitude (nmb_Dataset * dataset, nmm_Microscope_Remote * scope) {
  BCPlane * plane =
    dataset->inputGrid->getPlaneByName(buzzPlaneName.string());
  double val;

  val = plane->value(d_hapticSurface->getGridX(),
                    d_hapticSurface->getGridY());
  return (val - plane->minValue()) /
            (plane->maxValue() - plane->minValue());
}

// virtual
double nmui_GridFeatures::pointComplianceValue (nmb_Dataset * dataset, nmm_Microscope_Remote * scope) {
  BCPlane * plane =
    dataset->inputGrid->getPlaneByName(compliancePlaneName.string());

  if (!plane) {
    return nmui_SurfaceFeatureStrategy::pointComplianceValue(dataset, scope);
  }

  return plane->value(d_hapticSurface->getGridX(),
                      d_hapticSurface->getGridY());
}

// virtual
double nmui_GridFeatures::pointFrictionValue (nmb_Dataset * dataset, nmm_Microscope_Remote * scope) {
  BCPlane * plane = 
    dataset->inputGrid->getPlaneByName(frictionPlaneName.string());

  if (!plane) {
    return nmui_SurfaceFeatureStrategy::pointFrictionValue(dataset, scope);
  }

  return plane->value(d_hapticSurface->getGridX(),
                      d_hapticSurface->getGridY());
}

// virtual
double nmui_GridFeatures::scaledPointBumpSizeValue (nmb_Dataset * dataset, nmm_Microscope_Remote * scope) {
  BCPlane * plane =
    dataset->inputGrid->getPlaneByName(bumpPlaneName.string());
  double val;

  val = plane->value(d_hapticSurface->getGridX(),
                     d_hapticSurface->getGridY());
  return (val - plane->minValue()) /
            (plane->maxValue() - plane->minValue());
}



// virtual
double nmui_GridFeatures::magicBuzzAmplitude (double amp) {
  return 0.0001 + 0.0009 * amp;
}

// virtual
double nmui_GridFeatures::magicBumpSize (double wavelength) {
  return 0.0004 + 0.004 * wavelength;
}





