##############################################################################
#
# Typical stuff
#

include ../../../share/Makefile.common

include ../../../share/Makefile.root_common

### Put this at the END of the Makefile
include ../Makefile.additional-targets
