USES_LIBS := nmBase tclLinkVar nmAux vrpn vogl quat sdi

EXCLUDE_SRC = Microscope.C MicroscopeRcv.C MicroscopeIO.C MicroscopeIO.C \
	NetworkedMicroscopeChannel.C stm_file.c

NAUGHTY := 1

include ../Makefile.share
