#!/bin/sh

APP_DIR=$1;
shift;
APP_EXE=$1;

if [ -z "$HW_OS" ]; then
   uname=`uname`;
   if [ "${uname#CYGWIN}" != "$uname" ]; then
      HW_OS="pc_cygwin";
   else
      HW_OS=`hw_os`;
   fi
fi

if [ "$HW_OS" == "sgi_irix" ]; then
   if [ -z "$SGI_ABI" ]; then
      SGI_ABI=n32;
   fi
   if [ -z "$SGI_ARCH" ]; then
      SGI_ARCH=mips3;
   fi
   HW_OS=$HW_OS.$SGI_ABI.$SGI_ARCH;
fi

if [ -n "$MY_NANO_OBJ_DIR" ]; then
   FULL_EXE=$MY_NANO_OBJ_DIR/$HW_OS/$APP_DIR/$APP_EXE;
elif [ -n "$MY_NANO_SRC_DIR" ]; then
   FULL_EXE=$MY_NANO_SRC_DIR/nano/obj/$HW_OS/$APP_DIR/$APP_EXE;
elif [ "$HW_OS" != "pc_cygwin" ]; then
   FULL_EXE=/afs/unc/proj/stm/src/not_backed_up/$USER-nano/$HW_OS/$APP_DIR/$APP_EXE;
else
   FULL_EXE=/tmp/obj/$HW_OS/$APP_DIR/$APP_EXE;
fi

echo $FULL_EXE
