/* The nanoManipulator and its source code have been released under the
 * Boost software license when nanoManipulator, Inc. ceased operations on
 * January 1, 2014.  At this point, the message below from 3rdTech (who
 * sublicensed from nanoManipulator, Inc.) was superceded.
 * Since that time, the code can be used according to the following
 * license.  Support for this system is now through the NIH/NIBIB
 * National Research Resource at cismm.org.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <stdlib.h>
#include <stdio.h>
#include <math.h>

#include <GL/glut_UNC.h>

#include <nmb_Dataset.h>

#include "URender.h"
#include "ProjTextObjGenerator.h"

#include "quat.h"

// Created by Borland 04/26/02
// Handles the creation of Projective Texture Objects.  In essence, we use the UberGraphics functionality to 
// be able to control the transformation of projective textures through the object loading interface


#ifdef __CYGWIN__
// taken from WaveFrontFileGenerator.C
// XXX juliano 9/19/99
//       this was implicitly declared.  Needed to add decl.
//       getpid comes from unistd.h
#include <sys/types.h>  // for pid_t
extern "C" {
pid_t getpid();
}
#endif


extern nmb_Dataset * dataset;



ProjTextObjGenerator::ProjTextObjGenerator(const char *fname) : FileGenerator(fname, "ptx")
{
}


void BuildListProjTextObj(URender *Pobject, GLuint dl);


int ProjTextObjGenerator::ReLoad(URender *Pobject, GLuint *&Dlist_array) {
	return Load(Pobject, Dlist_array);
}



// This function creates a Projective Texture Object, used to control the transform for the Projective Texture
int ProjTextObjGenerator::Load(URender *Pobject, GLuint *&Dlist_array)
{
	GLuint dl;

	double minX, minY, maxX, maxY, z_value;

	// pointer to the current plane
	BCPlane *height = dataset->inputGrid->getPlaneByName(dataset->heightPlaneName->string());

	// set up min and max values for the current plane
	minX = height->minX();
	minY = height->minY();
	maxX = height->maxX();
	maxY = height->maxY();
	z_value = height->minNonZeroValue();

	//	set up display list id
	Dlist_array = new GLuint[1];
    dl = glGenLists(1);
    if (dl == 0 || Dlist_array == NULL) { 
		cerr << "Bad Display List generation\n"; 
        //kill(getpid(),SIGINT); 
        return 0;
	}
        
	BuildListProjTextObj(Pobject, dl);
		
	Dlist_array[0] = dl;

	// add minimum extents of the height plane
	Pobject->GetLocalXform().SetXOffset(minX);
	Pobject->GetLocalXform().SetYOffset(minY);
	Pobject->GetLocalXform().SetZOffset(z_value);

	Pobject->GetLocalXform().SetTranslate((maxX - minX) / 2, (maxY - minY) / 2, 0);

	return 1;	// number of display lists
}



void BuildListProjTextObj(URender *Pobject, GLuint dl) {
	// Create an object that will point in the direction of the projective texture...
	double radius = 200;
	double height = 800;
	double slices = 200;
	double stacks = 200;

	double width = radius / 8;
	double length = radius + 80.0;

	glNewList(dl, GL_COMPILE);	// init display list
	
	glColor3f(0.9, 0.4, 0.0);

	// draw cone
	glutSolidCone(radius, height, slices, stacks);

	// draw sight
	glBegin(GL_QUADS);
	// right side
	glVertex3d(width, 0.0, 0.0);
	glVertex3d(width, length, 0.0);
	glVertex3d(width, length, radius);
	glVertex3d(width, 0.0, radius);

	// left side
	glVertex3d(-width, 0.0, 0.0);
	glVertex3d(-width, length, 0.0);
	glVertex3d(-width, length, radius);
	glVertex3d(-width, 0.0, radius);

	// back
	glVertex3d(-width, 0.0, 0.0);
	glVertex3d(width, 0.0, 0.0);
	glVertex3d(width, 0.0, radius);
	glVertex3d(-width, 0.0, radius);

	// front
	glVertex3d(-width, length, 0.0);
	glVertex3d(width, length, 0.0);
	glVertex3d(width, length, radius);
	glVertex3d(-width, length, radius);

	// top
	glVertex3d(-width, 0.0, radius);
	glVertex3d(width, 0.0, radius);
	glVertex3d(width, length, radius);
	glVertex3d(-width, length, radius);
	glEnd();

	// draw center line
	glBegin(GL_LINES);
	glVertex3d(0.0, 0.0, 10000.0);
	glVertex3d(0.0, 0.0, -10000.0);
	glEnd();

	glEndList();
}
