/* The nanoManipulator and its source code have been released under the
 * Boost software license when nanoManipulator, Inc. ceased operations on
 * January 1, 2014.  At this point, the message below from 3rdTech (who
 * sublicensed from nanoManipulator, Inc.) was superceded.
 * Since that time, the code can be used according to the following
 * license.  Support for this system is now through the NIH/NIBIB
 * National Research Resource at cismm.org.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include "URVector.h"
#include "quat.h"
#include <GL/glut_UNC.h>

URVector::URVector(double start_x, double start_y, double start_z,
	  double dir_x, double dir_y, double dir_z):URender()
{
  set(start_x, start_y, start_z, dir_x, dir_y, dir_z);
  d_quadric = gluNewQuadric();
  gluQuadricDrawStyle(d_quadric, GLU_FILL);
  gluQuadricNormals(d_quadric, GLU_FLAT);
}

URVector::~URVector(){
  if (d_quadric) {
    gluDeleteQuadric(d_quadric);
  }
  return;
}

void URVector::set(double start_x, double start_y, double start_z,
	  double dir_x, double dir_y, double dir_z)
{
	d_start[0] = start_x; 
	d_start[1] = start_y; 
	d_start[2] = start_z;
	d_end[0] = start_x+dir_x; 
	d_end[1] = start_y+dir_y; 
	d_end[2] = start_z+dir_z;
}

int URVector::Render(void * /*userdata*/ )
{
  bool simpleModel = false;

  if(visible){
	glColor3f(1.0, 1.0, 1.0);
	q_type quat;
	q_vec_type v1 = {0.0, 0.0, 1.0};
	q_vec_type v2;
	v2[0] = d_end[0] - d_start[0];
	v2[1] = d_end[1] - d_start[1];
	v2[2] = d_end[2] - d_start[2];
	double vecLength = q_vec_magnitude(v2);
	q_vec_normalize(v2, v2);
	q_from_two_vecs(quat, v1, v2);
	qogl_matrix_type matrix;
	q_to_ogl_matrix(matrix, quat);
	glMatrixMode(GL_MODELVIEW);
	glPushMatrix();
	glTranslated(d_start[0], d_start[1], d_start[2]); 
	glMultMatrixd(matrix);
	if (simpleModel) {
		glBegin(GL_LINES);
		glVertex3d(0,0,0);
		glVertex3d(0,0,vecLength);
		glEnd();
	} else {
		double cylinderRadius = 0.05*vecLength;
		double cylinderLength = 0.6*vecLength;
		double coneRadius = 0.1*vecLength;
		double coneLength = 0.4*vecLength;
		gluCylinder(d_quadric, cylinderRadius, cylinderRadius, 
			cylinderLength, 30, 30);
		glTranslated(0.0,0.0,cylinderLength);
		gluDisk(d_quadric, 0.0, coneRadius, 30, 1);
		gluCylinder(d_quadric, coneRadius, 0.0, coneLength, 30,30);
	}
	glPopMatrix();
  }

  if(recursion) return  ITER_CONTINUE;
  else return ITER_STOP;
  
}