USES_LIBS := nmImageViewer nmMScope nmBase tclLinkVar nmGraphics \
             ImgFormat \
             vrpn vogl quat

USES_EXTERNAL_LIBS := glut

NAUGHTY := 1

EXCLUDE_SRC := warrencntsim.C

EXTRA_CFLAGS := -DNMRC_LIB

include ../Makefile.share
