USES_LIBS := nmImageViewer nmMScope nmBase tclLinkVar nmGraphics \
             ImgFormat \
             vrpn vogl quat

NAUGHTY := 1

EXCLUDE_SRC := warrencntsim.C

EXTRA_CFLAGS := -DNMRC_LIB

include ../Makefile.share
