USES_LIBS := nmBase ImgFormat nmGenTex nmMScope tclLinkVar nmUGraphics vrpn \
             vogl quat

USES_EXTERNAL_LIBS := RhinoIO

NAUGHTY := 1

EXCLUDE_SRC := nmg_GraphicsNull.C

include ../Makefile.share
