/* The nanoManipulator and its source code have been released under the
 * Boost software license when nanoManipulator, Inc. ceased operations on
 * January 1, 2014.  At this point, the message below from 3rdTech (who
 * sublicensed from nanoManipulator, Inc.) was superceded.
 * Since that time, the code can be used according to the following
 * license.  Support for this system is now through the NIH/NIBIB
 * National Research Resource at cismm.org.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/*===3rdtech===
  Copyright (c) 2000 by 3rdTech, Inc.
  All Rights Reserved.

  This file may not be distributed without the permission of 
  3rdTech, Inc. 
  ===3rdtech===*/
#include "nmg_State.h"
#include "nmg_Graphics.h" // for enums
#include "nmg_Surface.h"

#include "nmg_haptic_graphics.h"

class BCGrid;  // from BCGrid.h
class nmb_Subgrid;  // from nmb_Subgrid.h

// Attention:
// NO Tclvars in this file!  Nothing that needs to be shared outside!


nmg_State::nmg_State ()
{
    alphaTextureBlendFunc = GL_DECAL;
    alpha_r = 0.0f;
    alpha_g = 1.0f;
    alpha_b = 0.0f;
    alpha_slider_min = 0.0f;
    alpha_slider_max = 1.0f;

    colorMapDir = NULL;
    curColorMap = NULL;

    just_color = 0;

    color_min = 0; // nmb_ColorMap lower and upper bounds for color
    color_max = 1.0;

    displayIndexList = NULL;

    data_min_norm = 0; // nmb_ColorMap lower and upper bounds for data, normalized
    data_max_norm = 1.0;
    data_min = 0; // data min/max, real units.
    data_max = 1.0;

    opacity_slider_min = 0.0f;
    opacity_slider_max = 1.0f;

    textureDir = NULL;

    config_chartjunk = 1;
    config_measurelines = 1;
    config_planeonly = 0;
    config_filled_polygons = 1;
    config_smooth_shading = 1;
    config_trueTip = 0;
    config_enableUber = 1;

    //JM
    config_feelGrid = 0;
    config_feelPlane = 0;

    fg_xside = 0;
    fg_yside = 0;
    fg_vertices = NULL;


    contourTextureBlendFunc = GL_DECAL;
    contour_r = 255;
    contour_g = 55;
    contour_b = 55;
    contour_width = 10.0f;

    hand_color = 0;  
    null_data_alpha_toggle = 0;
    icon_scale = 0.25f;

    position_collab_hand = 0;
    draw_collab_hand = 0;
    collabMode = 0;

    surfaceColor[0] = 1.0f;
    surfaceColor[1] = 0.88f;
    surfaceColor[2] = 0.04f;
    surfaceColor[3] = 1.0f;

    // Colormap Textures:
    /* redundant
    colormap_texture_curColorMap = NULL;
    colormap_texture_data_min = 0;
    colormap_texture_data_max = 1.0;
    colormap_texture_color_min = 0;
    colormap_texture_color_max = 1.0;
    colormap_texture_name[0] = '\0';
    */

    prerendered_grid = NULL;
    prerenderedChange = NULL;

    // Registration
    surfaceModeTextureTransform[0] = 0.001;
    surfaceModeTextureTransform[1] = 0;
    surfaceModeTextureTransform[2] = 0;
    surfaceModeTextureTransform[3] = 0;
    surfaceModeTextureTransform[4] = 0;
    surfaceModeTextureTransform[5] = 0.001;
    surfaceModeTextureTransform[6] = 0;
    surfaceModeTextureTransform[7] = 0;
    surfaceModeTextureTransform[8] = 0;
    surfaceModeTextureTransform[9] = 0;
    surfaceModeTextureTransform[10] = 1;
    surfaceModeTextureTransform[11] = 0;
    surfaceModeTextureTransform[12] = 0;
    surfaceModeTextureTransform[13] = 0;
    surfaceModeTextureTransform[14] = 0;
    surfaceModeTextureTransform[15] = 1;

    scanlinePt [0] = 0.0;
    scanlinePt [1] = 0.0;
    scanlinePt [2] = 0.0;
    scanlinePt [3] = 0.0;
    scanlinePt [4] = 0.0;
    scanlinePt [5] = 0.0;
    scanline_display_enabled = 0;

    rulergrid_xoffset = 0.0f;
    rulergrid_yoffset = 0.0f;
    rulergrid_scale = 500.0f;
    ruler_r = 255;
    ruler_g = 255;
    ruler_b = 55;

    //set default rulergrid opacity to 178 (70%) instead of 255 (100%)
    ruler_opacity = 178.0f;
    ruler_width_x = 1.0f;
    ruler_width_y = 1.0f;
    rulergrid_sin = 0.0f;
    rulergrid_cos = 1.0f;
    rulerPPM = NULL;

    // Material properties of the surface
    shiny = 55;
    local_viewer = vrpn_TRUE;
    diffuse = .50;
    specular_color = 1.0;

    surface_alpha = 1.0;

    sphere_scale = 12.5f;
    stride = 1;

    xs_state[0].enabled = 0;
    xs_state[1].enabled = 0;

    texture_displayed = nmg_Graphics::NO_TEXTURES;
    texture_transform_mode = nmg_Graphics::RULERGRID_COORD;
	currentProjectiveTexture = NULL;

    texture_mode = GL_FALSE;

    texture_scale = 10.0f;
    trueTipScale = 1.0f;

    PRERENDERED_COLORS = 0;  // only used by remote rendering clients
    PRERENDERED_TEXTURE = 0;  // only used by remote rendering clients
    PRERENDERED_DEPTH = 0;  // only used by remote rendering clients

    inputGrid = NULL;

    mask = ENABLE_MASK;
    transparent = 0;
    viztex_scale = 500.0f;

    vizPPM = NULL;

    //////////////////////////////////////////////////////////////////
    // Variables that define what GL can and can't do on the machine
    // we are running on.
    //////////////////////////////////////////////////////////////////

    VERTEX_ARRAY = 0;

    //////////////////////////////////////////////////////////////////
    // End GL capabilities
    //////////////////////////////////////////////////////////////////
}

// Local Variables:
// mode:c++
// End:
