/* The nanoManipulator and its source code have been released under the
 * Boost software license when nanoManipulator, Inc. ceased operations on
 * January 1, 2014.  At this point, the message below from 3rdTech (who
 * sublicensed from nanoManipulator, Inc.) was superceded.
 * Since that time, the code can be used according to the following
 * license.  Support for this system is now through the NIH/NIBIB
 * National Research Resource at cismm.org.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/*      This structure holds information about a pulse that is used to
 * display a marker at the pulse location. */

#ifndef	SURFACE_STRIP_CREATE_H
#define	SURFACE_STRIP_CREATE_H

#ifndef NMB_PLANE_SELECTION_H
#include <nmb_PlaneSelection.h>
#endif

class BCGrid;  // from BCGrid.h
class nmg_SurfaceMask;
class nmg_State;

// structure for vertex array
struct Vertex_Struct;


extern int spm_x_strip (nmg_State * state, const nmb_PlaneSelection &planes,
                        GLdouble surfaceColor [3], int which,
                        Vertex_Struct * vertexArray);
extern int spm_x_strip_masked (nmg_State * state, const nmb_PlaneSelection &planes, 
                               nmg_SurfaceMask *mask,
                               GLdouble surfaceColor [3], int which,
                               Vertex_Struct * vertexArray);
extern int spm_y_strip (nmg_State * state, const nmb_PlaneSelection &planes,
                        GLdouble surfaceColor [3], int which,
                        Vertex_Struct * vertexArray);
extern int spm_y_strip_masked (nmg_State * state, const nmb_PlaneSelection &planes, 
                               nmg_SurfaceMask *mask,
                               GLdouble surfaceColor [3], int which,
                               Vertex_Struct * vertexArray);
extern	int	spm_grid_to_tris (BCGrid *, GLdouble *, GLdouble *, int);
//extern	void	spm_show_location_indicators (int total_num,
//                     nmb_LocationInfo [], int num_to_show, int last_one);
#endif  /* SPM_GL_H */















