/* The nanoManipulator and its source code have been released under the
 * Boost software license when nanoManipulator, Inc. ceased operations on
 * January 1, 2014.  At this point, the message below from 3rdTech (who
 * sublicensed from nanoManipulator, Inc.) was superceded.
 * Since that time, the code can be used according to the following
 * license.  Support for this system is now through the NIH/NIBIB
 * National Research Resource at cismm.org.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef NMR_ALIGNERMI_H
#define NMR_ALIGNERMI_H

#include "nmb_Image.h"
#include "nmr_MultiResObjectiveMI_direct.h"
#include "nmb_Transform_TScShR.h"

class nmr_AlignerMI {
  public:
    nmr_AlignerMI();
    ~nmr_AlignerMI();

    void initImages(nmb_Image *ref, nmb_Image *test, nmb_Image *ref_z = NULL,
                    nmb_ImageList *monitorList = NULL);
    void initImages(nmb_Image *ref, nmb_Image *test, 
                    int numLevels, float *stddev, 
                    nmb_Image *ref_z = NULL, nmb_ImageList *monitorList = NULL);
//    void optimizeVarianceParameters();
    void optimizeTransform();
    void takeGradientSteps(int resolutionIndex, int numSteps, float stepSize);
    void multiResPatternSearch(int maxIterations, float translationStepSize);
    int patternSearch(int resolutionIndex, 
                       int numPatternMoves, float stepSize, float minStepSize);

    // transform is assumed to be in pixel units
    void setTransform(nmb_Transform_TScShR &xform);
    void getTransform(nmb_Transform_TScShR &xform);
    void printJointHistograms(nmb_Transform_TScShR &xform);
    void plotObjective(FILE *outf);
    int getNumLevels();
    void getBlurStdDev(float *stddev);
//    void setRefFeaturePoints(int numPnts, double *x, double *y);

  protected:
    nmr_MultiResObjectiveMI_direct *d_objective;
    nmb_Transform_TScShR d_transform;
    int d_refWidth, d_refHeight;
    int d_testWidth, d_testHeight;
};

#endif
