USES_LIBS := nmMScope tclLinkVar nmBase vrpn

# EXTRA_CFLAGS := -I/afs/unc/proj/walk/include

LATE_INCLUDE_PATH := -I/afs/unc/proj/walk/include
LATE_LOAD_PATH := -L/afs/unc/proj/walk/lib/$(HW_OS).$(SGI_ABI)


include ../Makefile.share
