USES_LIBS := nmMScope tclLinkVar nmBase nmMP vrpn

# EXTRA_CFLAGS := -I/afs/unc/proj/walk/include

LATE_INCLUDE_PATH := -I/afs/unc/proj/stm/src/external/glut-3.5/include \
 -I/afs/unc/proj/stm/src/external/glui-2
LATE_LOAD_PATH := -L/afs/unc/proj/stm/src/external/glut-3.5/lib/glut.n32 \
 -L/afs/unc/proj/stm/src/external/glui-2/sgi_irix.n32.mips3
LATE_LIBRARIES :=

# We're not going to get glui there, but we need to specify SOMETHING
# so it looks there for Tcl

USES_EXTERNAL_LIBS := tcl



include ../Makefile.share
